apiVersion: v1
kind: Service
metadata:
  name: dronecrisis
  namespace: default
spec:
  selector:
    app: dronecrisis
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
